name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}

    - name: Add Pantheon remote
      run: |
        git remote add pantheon ${{ secrets.PANTHEON_SSH_URL }}
        git fetch pantheon

    
    - name: Push to Pantheon
      run: git push pantheon master