name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Add Pantheon remote
      run: |
        git remote add pantheon ${{ secrets.PANTHEON_SSH_URL }}
        git fetch pantheon
    
    # - name: Push to Pantheon
    #   run: git push pantheon master